data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"  # Add this line
  chunk_size: 512
  overlap: 50

embedding:
  model_type: "openai"
  model_name: "text-embedding-3-large" # "distilbert-base-uncased"
  device: "cuda"
  train:
    enabled: true
    output_path: "deepraghub/data/embeddings"
    epochs: 4
    batch_size: 16
    eval_steps: 100
    save_steps: 100
    fp16: true
    push_to_hub: false
    hub_model_id: "your-username/your-model-name" 

retrieval:
  vector_db_name: "in_memory"
  vector_db_url: ""
  collection_name: "test_collection"
  top_k: 5

generation:
  model_type: "openai"
  model_name: "gpt-4o"
  max_length: 512
  temperature: 0.7

rag:
  max_context_size: 4096
  top_k_docs: 5