data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"  # Add this line
  chunk_size: 512
  overlap: 50

embedding:
  model_type: "custom"
  model_name: "distilbert-base-uncased" # "distilbert-base-uncased"
  device: "cuda"
  train:
    enabled: true
    dataset_source: "huggingface"
    dataset_name: "sentence-transformers/stsb"
    dataset_path: "deepraghub/data/processed/training_data.jsonl"
    output_path: "models/embeddings"
    num_epochs: 10
    batch_size: 16
    learning_rate: 2e-5
    eval_steps: 100
    save_steps: 100
    fp16: true
    push_to_hub: false
    hub_model_id: "your-username/your-model-name" 

retrieval:
  vector_db_name: "in_memory"
  vector_db_url: ""
  collection_name: "test_collection"
  top_k: 5

generation:
  model_type: "openai"
  model_name: "gpt-4o"
  max_length: 512
  temperature: 0.7

rag:
  max_context_size: 4096
  top_k_docs: 5